#!/usr/bin/env bash
# faham 部署脚本
#
# 为什么存在：wrangler pages deploy 上传目录内的「所有实际文件」，
# 与 .gitignore 无关。曾因此把 .env 传上公网。
# 因此本脚本采用白名单：只把该公开的文件复制进 public/ 再部署，
# 并在部署后自动验证敏感路径确实不可访问。
#
# 用法：  ./deploy.sh dev     （预览，带样例数据）
#         ./deploy.sh main    （正式，空架构）
set -euo pipefail

BRANCH="${1:-dev}"
PROJECT="${PAGES_PROJECT:-faham}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/public"

# 本脚本打包的是「工作区当前的文件」，不是目标分支的文件。
# 在 main 上跑 ./deploy.sh dev，上线的会是 main 的空数据——曾经就这么把 dev 清空过。
CUR="$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
if [ "$CUR" != "$BRANCH" ]; then
  echo "✗ 当前在 $CUR 分支，却要部署 $BRANCH。"
  echo "  先切过去：git checkout $BRANCH"
  echo "  （如确定要用当前工作区的内容部署到 $BRANCH，加 --force-branch）"
  [ "${2:-}" = "--force-branch" ] || exit 1
fi

echo "▸ 重建 public/（白名单）"
rm -rf "$OUT"
mkdir -p "$OUT/data" "$OUT/db" "$OUT/docs" "$OUT/assets"

cp "$ROOT/index.html"                "$OUT/"
cp "$ROOT/data/events.json"          "$OUT/data/"
cp "$ROOT"/data/threads.json "$ROOT"/data/actors.json "$OUT/data/" 2>/dev/null || true
cp "$ROOT/db/schema.sql" "$ROOT/db/live.sql" "$OUT/db/"
cp "$ROOT"/docs/*.md                 "$OUT/docs/"
cp "$ROOT/assets/og.png"             "$OUT/assets/"        # 社交分享预览图
cp "$ROOT"/README*.md                "$OUT/" 2>/dev/null || true
cp "$ROOT/LICENSE" "$ROOT/LICENSE-CONTENT" "$OUT/" 2>/dev/null || true

# Pages Functions（/api/*）不复制进 public/：
# wrangler 是从「资产目录的同级」——也就是仓库根的 functions/ ——打包 Functions 的，
# 不是从资产目录里面。曾经把生成的 _env.js 写进 public/functions/，结果 main
# 上线后打包进去的仍是 dev 那一份，生产写进了 dev 桶。
#
# 数据隔离：dev 与 prod 共用一个 Neon 库，靠这个常量分桶写入。
# 由部署脚本生成而非在仪表板配置，是为了让「这次部署写进哪个桶」留在版本记录里。
APP_ENV=$([ "$BRANCH" = "main" ] && echo prod || echo dev)
printf "// generated by deploy.sh — do not edit\nexport const APP_ENV = '%s';\n" "$APP_ENV" \
  > "$ROOT/functions/_env.js"
# 部署结束后把仓库里的默认值还原成 dev，避免工作区被脚本改脏
trap 'printf "%s" "// 本文件由 deploy.sh 在打包时覆写，用于区分 dev 与 prod 的数据隔离。
// 仓库里保留的默认值是 dev —— 本地 \`wrangler pages dev\` 直接可用，
// 且万一部署脚本没跑到这一步，写入的也是 dev 桶，不会污染正式站。
export const APP_ENV = '"'"'dev'"'"';
" > "$ROOT/functions/_env.js"' EXIT
echo "  ✓ APP_ENV=$APP_ENV"

# 非生产分支：注入 noindex，避免预览版（含未溯源的样品数据）被搜索引擎收录
if [ "$BRANCH" != "main" ]; then
  python3 - "$OUT/index.html" <<'PY'
import sys, re
p = sys.argv[1]; s = open(p, encoding='utf-8').read()
tag = '<meta name="robots" content="noindex, nofollow">\n'
if 'name="robots"' not in s:
    s = s.replace('<meta charset="utf-8">', '<meta charset="utf-8">\n' + tag, 1)
    open(p, 'w', encoding='utf-8').write(s)
PY
  printf 'User-agent: *\nDisallow: /\n' > "$OUT/robots.txt"
  echo "  ✓ 预览分支：已注入 noindex + robots.txt"
fi

echo "▸ 部署前安全检查"
if find "$OUT" \( -name '.env*' -o -name '*.local.*' -o -name '.git*' \
                  -o -name 'skills-lock*' -o -name '.dev.vars' \) | grep -q .; then
  echo "  ✗ public/ 内发现敏感文件，已中止"; exit 1
fi
# 机密只能来自 Cloudflare secret。若有人把连接串写死进 Functions，这里拦下来。
if grep -rIl 'postgresql://\|postgres://' "$OUT" >/dev/null 2>&1; then
  echo "  ✗ 打包内容里出现数据库连接串，已中止"; exit 1
fi
echo "  ✓ public/ 干净（$(find "$OUT" -type f | wc -l | tr -d ' ') 个文件）"

# 只打包不部署：给本地 `npx wrangler pages dev public` 用，
# 保证本地跑的就是将要上线的那一份文件，而不是仓库根目录。
if [ "${2:-}" = "--build-only" ]; then
  echo "▸ 仅打包完成：$OUT"; exit 0
fi

echo "▸ 部署到分支 $BRANCH"
npx wrangler pages deploy "$OUT" --project-name="$PROJECT" --branch="$BRANCH" --commit-dirty=true

echo "▸ 部署后验证敏感路径不可访问"
sleep 6
# 生产分支没有分支前缀：main 走裸域名，其余分支走 <branch>. 别名
HOST="${PAGES_HOST:-$PROJECT}"
if [ "$BRANCH" = "main" ]; then URL="https://${HOST}.pages.dev"
else URL="https://${BRANCH}.${HOST}.pages.dev"; fi
fail=0
for p in .env .dev.vars .gitignore skills-lock.json .git/config data/events.local.json functions/_lib.js; do
  code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 12 "$URL/$p" || echo 000)
  body=$(curl -s --max-time 12 "$URL/$p" 2>/dev/null | head -c 200 || true)
  # Pages 对未知路径回退到 index.html，故以「是否为 HTML 页面」判定，忽略大小写
  if [ "$code" = "200" ] && ! printf '%s' "$body" | grep -qi '<!doctype html\|<html'; then
    echo "  ✗ 泄露：$URL/$p"; fail=1
  else
    echo "  ✓ $p 不可访问"
  fi
done
[ "$fail" = "0" ] || { echo "▸ 发现泄露，请立即删除该部署"; exit 1; }

echo "▸ 后端自检 /api/health"
health=$(curl -s --max-time 15 "$URL/api/health" || echo '{}')
case "$health" in
  *'"db":"up"'*)   echo "  ✓ 数据库已接通 $health" ;;
  *'"db":"down"'*) echo "  ⚠ Functions 已上线，但连不上数据库——检查 DATABASE_URL secret" ;;
  *)               echo "  ⚠ /api/health 无响应：Functions 可能未部署。返回：${health:0:120}" ;;
esac

echo "▸ 完成：$URL"
